// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCQ3_xk6D78AMGYdlZh0L3QoO_tTEMg4',
    appId: '1:467487435625:web:954c4a6e57cfe4d8196bf8',
    messagingSenderId: '467487435625',
    projectId: 'sdc-refugee-help',
    authDomain: 'sdc-refugee-help.firebaseapp.com',
    storageBucket: 'sdc-refugee-help.appspot.com',
    measurementId: 'G-ZD4PP3SJK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbeymXyIzOJT9i-BAjSrQpAJ8OIOM4QM',
    appId: '1:467487435625:android:bc528748aba5da0c196bf8',
    messagingSenderId: '467487435625',
    projectId: 'sdc-refugee-help',
    storageBucket: 'sdc-refugee-help.appspot.com',
  );
}
